global:
  scrape_interval: 15s

scrape_configs:
  # Backend Service
  - job_name: 'backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:3000']

  # Analytics Service (if you’ve instrumented it; otherwise omit)
  - job_name: 'analytics-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['analytics-service:4002']

  # (Optional) Prometheus’s own metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
